# Configuration IA Chatbot pour primes-services.ia
# =================================================

development:
  openai:
    api_key: <%= ENV.fetch("OPENAI_API_KEY") { "your_openai_api_key_here" } %>
    model: <%= ENV.fetch("OPENAI_MODEL") { "gpt-4o-mini" } %>
    max_tokens: <%= ENV.fetch("OPENAI_MAX_TOKENS") { 2000 } %>
    temperature: <%= ENV.fetch("OPENAI_TEMPERATURE") { 0.3 } %>

  assistant:
    name: <%= ENV.fetch("AI_ASSISTANT_NAME") { "Assistant Primes Services" } %>
    language: <%= ENV.fetch("AI_LANGUAGE") { "fr-BE" } %>
    fallback_language: <%= ENV.fetch("AI_FALLBACK_LANGUAGE") { "fr" } %>

  regions:
    default: <%= ENV.fetch("DEFAULT_REGION") { "wallonie" } %>
    supported: <%= ENV.fetch("SUPPORTED_REGIONS") { "wallonie,flandre,bruxelles" }.split(",") %>

  integrations:
    renovate_base_url: <%= ENV.fetch("RENOVATE_BASE_URL") { "https://ren0vate.primes/" } %>
    team_email: <%= ENV.fetch("TEAM_EMAIL") { "equipe@primes-services.be" } %>

  debug:
    enabled: <%= ENV.fetch("AI_DEBUG_MODE") { true } %>
    log_conversations: <%= ENV.fetch("AI_LOG_CONVERSATIONS") { true } %>

  cache:
    enabled: <%= ENV.fetch("AI_CACHE_ENABLED") { true } %>
    duration: <%= ENV.fetch("AI_CACHE_DURATION") { 3600 } %>

test:
  openai:
    api_key: "test_api_key"
    model: "gpt-3.5-turbo"
    max_tokens: 1000
    temperature: 0.1

  assistant:
    name: "Assistant Test"
    language: "fr-BE"
    fallback_language: "fr"

  regions:
    default: "wallonie"
    supported: ["wallonie", "flandre", "bruxelles"]

  debug:
    enabled: true
    log_conversations: false

  cache:
    enabled: false
    duration: 300

production:
  openai:
    api_key: <%= ENV.fetch("OPENAI_API_KEY") %>
    model: <%= ENV.fetch("OPENAI_MODEL") { "gpt-4o-mini" } %>
    max_tokens: <%= ENV.fetch("OPENAI_MAX_TOKENS") { 2000 } %>
    temperature: <%= ENV.fetch("OPENAI_TEMPERATURE") { 0.3 } %>

  assistant:
    name: <%= ENV.fetch("AI_ASSISTANT_NAME") { "Assistant Primes Services" } %>
    language: <%= ENV.fetch("AI_LANGUAGE") { "fr-BE" } %>
    fallback_language: <%= ENV.fetch("AI_FALLBACK_LANGUAGE") { "fr" } %>

  regions:
    default: <%= ENV.fetch("DEFAULT_REGION") { "wallonie" } %>
    supported: <%= ENV.fetch("SUPPORTED_REGIONS") { "wallonie,flandre,bruxelles" }.split(",") %>

  integrations:
    renovate_base_url: <%= ENV.fetch("RENOVATE_BASE_URL") %>
    team_email: <%= ENV.fetch("TEAM_EMAIL") %>

  debug:
    enabled: false
    log_conversations: <%= ENV.fetch("AI_LOG_CONVERSATIONS") { false } %>

  cache:
    enabled: <%= ENV.fetch("AI_CACHE_ENABLED") { true } %>
    duration: <%= ENV.fetch("AI_CACHE_DURATION") { 3600 } %>
